import * as pdfjsLib from 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs';
const { PDFDocument, rgb, StandardFonts } = window.PDFLib;
pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';
const $=id=>document.getElementById(id); let pdfBytes=null,pdfDoc=null,pages=[],activePage=0,tool='select',selected=null,objects=[];
const status=m=>$('status').textContent=m;
function setTool(t){tool=t;document.querySelectorAll('.tool[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));}
document.querySelectorAll('.tool[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));
$('pdfInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;pdfBytes=new Uint8Array(await f.arrayBuffer());await loadPDF();};
async function loadPDF(){pdfDoc=await pdfjsLib.getDocument({data:pdfBytes}).promise; pages=[];objects=[];$('pages').innerHTML='';$('emptyState').style.display='none';for(let i=1;i<=pdfDoc.numPages;i++){const p=await pdfDoc.getPage(i);pages.push(p);const th=document.createElement('div');th.className='thumb';th.dataset.page=i-1;const c=document.createElement('canvas');const vp=p.getViewport({scale:.22});c.width=vp.width;c.height=vp.height;await p.render({canvasContext:c.getContext('2d'),viewport:vp}).promise;th.append(c);const s=document.createElement('span');s.textContent=`Page ${i}`;th.append(s);th.onclick=()=>showPage(i-1);$('pages').append(th)}$('downloadBtn').disabled=false;showPage(0);status(`${pdfDoc.numPages} page(s) loaded locally.`)}
async function showPage(i){activePage=i;document.querySelectorAll('.thumb').forEach(x=>x.classList.toggle('active',+x.dataset.page===i));const p=pages[i];const vp=p.getViewport({scale:1.5});const shell=document.createElement('div');shell.className='page-shell';shell.style.width=vp.width+'px';shell.style.height=vp.height+'px';const c=document.createElement('canvas');c.width=vp.width;c.height=vp.height;shell.append(c);const ov=document.createElement('div');ov.className='overlay';shell.append(ov);$('canvasWrap').innerHTML='';$('canvasWrap').append(shell);await p.render({canvasContext:c.getContext('2d'),viewport:vp}).promise;await extractText(p,vp,ov,i);renderObjects(i,ov,vp)}
async function extractText(p,vp,ov,pageIndex){const tc=await p.getTextContent();const pageObjects=objects.filter(o=>o.page===pageIndex&&o.kind==='text');if(pageObjects.length)return;for(const item of tc.items){if(!item.str.trim())continue;const tx=pdfjsLib.Util.transform(vp.transform,item.transform);const fontSize=Math.hypot(tx[0],tx[1]);const x=tx[4],y=tx[5]-fontSize;const w=item.width*1.5,h=fontSize*1.2;pageObjects.push({id:crypto.randomUUID(),page:pageIndex,kind:'sourceText',text:item.str,x,y,w,h,size:fontSize,font:'Helvetica',color:'#111111',opacity:0.01,original:true})}objects.push(...pageObjects)}
function renderObjects(pageIndex,ov,vp){ov.innerHTML='';for(const o of objects.filter(x=>x.page===pageIndex&&!x.original)){drawObj(o,ov)}for(const o of objects.filter(x=>x.page===pageIndex&&x.original)){const el=document.createElement('div');el.className='obj text';el.style.cssText=`left:${o.x}px;top:${o.y}px;width:${o.w}px;height:${o.h}px;font-size:${o.size}px;color:transparent;background:transparent;`;el.title='Click to replace this text';el.onclick=e=>{e.stopPropagation();startReplace(o)};ov.append(el)}}
function drawObj(o,ov){const el=document.createElement(o.kind==='image'?'img':'div');el.className='obj '+(o.kind==='image'?'image-obj':'text');el.dataset.id=o.id;el.style.left=o.x+'px';el.style.top=o.y+'px';el.style.width=o.w+'px';el.style.height=o.h+'px';el.style.opacity=o.opacity??1;if(o.kind==='image'){el.src=o.src}else{el.textContent=o.text;el.style.fontSize=o.size+'px';el.style.fontFamily=o.font;el.style.color=o.color;el.style.lineHeight='1.1'}el.onclick=e=>{e.stopPropagation();select(o)};ov.append(el)}
function select(o){selected=o;$('propsEmpty').hidden=true;$('props').hidden=false;$('propText').value=o.text||'';$('propSize').value=o.size||16;$('propOpacity').value=o.opacity??1;$('propFont').value=o.font||'Helvetica';$('propColor').value=o.color||'#111111';}
function startReplace(source){setTool('text');const o={id:crypto.randomUUID(),page:activePage,kind:'text',text:source.text,x:source.x,y:source.y,w:Math.max(source.w,40),h:source.h,size:source.size,font:'Helvetica',color:'#111111',opacity:1,replaceSource:source.id};objects.push(o);select(o);status('Replacement text created over the selected PDF text. Edit it in Properties.');showPage(activePage)}
$('canvasWrap').onclick=e=>{if(e.target!==$('canvasWrap'))return};
$('canvasWrap').addEventListener('dblclick',e=>{if(tool!=='text'&&tool!=='cover')return;const shell=e.target.closest('.page-shell');if(!shell)return;const r=shell.getBoundingClientRect();const x=e.clientX-r.left,y=e.clientY-r.top;if(tool==='text'){const o={id:crypto.randomUUID(),page:activePage,kind:'text',text:'New text',x,y,w:220,h:40,size:18,font:'Helvetica',color:'#111111',opacity:1};objects.push(o);select(o);showPage(activePage)}else{const o={id:crypto.randomUUID(),page:activePage,kind:'cover',x:x-40,y:y-15,w:120,h:35,color:'#fff'};objects.push(o);showPage(activePage)}});
$('imageInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;const src=await fileData(f);const o={id:crypto.randomUUID(),page:activePage,kind:'image',src,x:80,y:80,w:180,h:100,opacity:1};objects.push(o);select(o);showPage(activePage)};
$('applyProps').onclick=()=>{if(!selected)return;selected.text=$('propText').value;selected.size=+$('propSize').value;selected.opacity=+$('propOpacity').value;selected.font=$('propFont').value;selected.color=$('propColor').value;showPage(activePage)};
$('deleteSelected').onclick=()=>{if(!selected)return;objects=objects.filter(o=>o!==selected);selected=null;$('props').hidden=true;$('propsEmpty').hidden=false;showPage(activePage)};
async function fileData(f){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f)})}
function hexRgb(h){h=h.replace('#','');return rgb(parseInt(h.slice(0,2),16)/255,parseInt(h.slice(2,4),16)/255,parseInt(h.slice(4,6),16)/255)}
async function exportPDF(){if(!pdfBytes)return;status('Building modified PDF…');const out=await PDFDocument.load(pdfBytes);const fonts={Helvetica:await out.embedFont(StandardFonts.Helvetica),'Helvetica-Bold':await out.embedFont(StandardFonts.HelveticaBold),'Times-Roman':await out.embedFont(StandardFonts.TimesRoman),'Times-Bold':await out.embedFont(StandardFonts.TimesBold),Courier:await out.embedFont(StandardFonts.Courier),'Courier-Bold':await out.embedFont(StandardFonts.CourierBold)};for(let i=0;i<out.getPageCount();i++){const page=out.getPage(i),{width,height}=page.getSize(),scale=1.5;for(const o of objects.filter(x=>x.page===i)){if(o.kind==='cover'||o.replaceSource){const s=o.replaceSource?objects.find(x=>x.id===o.replaceSource):o;if(s)page.drawRectangle({x:s.x/scale,y:height-(s.y+s.h)/scale,width:s.w/scale,height:s.h/scale,color:rgb(1,1,1),opacity:1});}if(o.kind==='cover'){page.drawRectangle({x:o.x/scale,y:height-(o.y+o.h)/scale,width:o.w/scale,height:o.h/scale,color:rgb(1,1,1)});}if(o.kind==='text'){page.drawText(o.text,{x:o.x/scale,y:height-(o.y+o.size)/scale,size:o.size/scale,font:fonts[o.font]||fonts.Helvetica,color:hexRgb(o.color),opacity:o.opacity??1,maxWidth:o.w/scale,lineHeight:o.size/scale*1.15});}if(o.kind==='image'){const bytes=await fetch(o.src).then(r=>r.arrayBuffer());let img;try{img=await out.embedPng(bytes)}catch{img=await out.embedJpg(bytes)}page.drawImage(img,{x:o.x/scale,y:height-(o.y+o.h)/scale,width:o.w/scale,height:o.h/scale,opacity:o.opacity??1})}}}const data=await out.save();const blob=new Blob([data],{type:'application/pdf'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='modified-pdf.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);status('Export complete.');}
$('downloadBtn').onclick=exportPDF;
